// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGKqhloD3M3EZs_frlLNoyMWykta52AMQ',
    appId: '1:801951855531:web:b887909be815b4994b58ee',
    messagingSenderId: '801951855531',
    projectId: 'projectmedi-46b08',
    authDomain: 'projectmedi-46b08.firebaseapp.com',
    storageBucket: 'projectmedi-46b08.appspot.com',
    measurementId: 'G-0F99T3DF8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgWyUBEfIYbxopDnZxWd1MA8ICnLBlrao',
    appId: '1:801951855531:android:13041c39776749b34b58ee',
    messagingSenderId: '801951855531',
    projectId: 'projectmedi-46b08',
    storageBucket: 'projectmedi-46b08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWUpYK0E1aYLwzPrYF1qOgEs9tEieThIc',
    appId: '1:801951855531:ios:76d970dd97cfd07b4b58ee',
    messagingSenderId: '801951855531',
    projectId: 'projectmedi-46b08',
    storageBucket: 'projectmedi-46b08.appspot.com',
    iosBundleId: 'com.example.mediMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWUpYK0E1aYLwzPrYF1qOgEs9tEieThIc',
    appId: '1:801951855531:ios:76d970dd97cfd07b4b58ee',
    messagingSenderId: '801951855531',
    projectId: 'projectmedi-46b08',
    storageBucket: 'projectmedi-46b08.appspot.com',
    iosBundleId: 'com.example.mediMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGKqhloD3M3EZs_frlLNoyMWykta52AMQ',
    appId: '1:801951855531:web:f8c030a15aada5734b58ee',
    messagingSenderId: '801951855531',
    projectId: 'projectmedi-46b08',
    authDomain: 'projectmedi-46b08.firebaseapp.com',
    storageBucket: 'projectmedi-46b08.appspot.com',
    measurementId: 'G-QV7V3NBZX6',
  );
}
